# spring.application.name=sportsceter

server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/webapp?createDatabaseIfNotExist=true
        username: root
        password: mysql
        driver-class-name: com.mysql.cj.jdbc.Driver
    application:
        name: webapp
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect    
                format_sql: true

    
    