# spring.application.name=sportsceter

server:
    port: 8081

spring:
    config:
        import: optional:file:.env[.properties]
    sql:
        init:
            mode: always
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    application:
        name: webapp
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect    
                format_sql: true
    h2:
        console:
            enabled: true
    
logging:
  level:
    root: INFO
    com.tdunning.statsd: INFO
  file:
    name: /var/log/statsd/csye6225.log

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET_NAME}