# spring.application.name=sportsceter

server:
    port: 8080

spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    application:
        name: webapp
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect    
                format_sql: true

    
    