name: Build Packer Custom AMI

on:
  pull_request:
    types: [closed]
  # push:
    branches:
      - main

jobs:
  build-ami:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      #checkout the repository
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven


      #run the integration tests
      - name: Integration tests
        run: mvn test
      
      #build the application artifact
      - name: Build the application artifact
        run: mvn clean package -DskipTests
      
      #configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      #install packer
      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer

      #build the AMI using packer
      - name: Build the AMI using Packer
        run: |
          cd packer
          packer init webapp-ami-us-west-2.pkr.hcl
          packer build webapp-ami-us-west-2.pkr.hcl
 
          